### ISSUE TITLE
Does not work when the Secure Boot is enabled (failed to get I/O permission)

### ISSUE THREAD

**Issue by szydell** [pop-os/system76-firmware#127]
**Distribution (run `cat /etc/os-release`):**
NAME="Fedora Linux"
VERSION="39 (KDE Plasma)"
ID=fedora
VERSION_ID=39
VERSION_CODENAME=""
PLATFORM_ID="platform:f39"
PRETTY_NAME="Fedora Linux 39 (KDE Plasma)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:39"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f39/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=39
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=39
SUPPORT_END=2024-05-14
VARIANT="KDE Plasma"
VARIANT_ID=kde
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Current version for GitHub packaged for Fedora.

**Issue/Bug Description:**
[root@ ~]# system76-firmware-daemon 
system76-firmware-daemon: failed to get I/O permission: Operation not permitted (os error 1)

The issue is related to Secure Boot and kernel lockdown. I was able to reproduce it and found a workaround. With the disabled secure boot, it works ok again.

As written in the man (https://man7.org/linux/man-pages/man2/iopl.2.html) usage of iopl is deprecated. Maybe there is a way to rewrite this part? :)
```    // Get I/O Permission
    if unsafe { libc::iopl(3) } < 0 {
        return Err(format!(
            "failed to get I/O permission: {}",
            io::Error::last_os_error()
        ));
    }
```
**Steps to reproduce (if you know):**
You can just run it on a system with enabled Secure Boot.

**Expected behavior:**
Run also on systems with enabled Secure Boot.

**Other Notes:**
Originally reported as an issue for Fedora copr package here: https://pagure.io/system76/system76-firmware/issue/1

**Comment by s373r** [comment]
I have the exact same problem

**Comment by tunix** [comment]
Any chance that this may get fixed soon?

**Comment by kp9001** [comment]
I think iopl((3) is required the way this is written because the program is trying to open /dev/port and /dev/mem in some places, which is restricted by the kernel. For example, if I run system76-firmware-cli with the ipol(3) blocks removed, 

```
thread 'main' panicked at <home>/.cargo/git/checkouts/ecflash-90320af7ef020fdf/ee9d69d/src/io.rs:11:14:
failed to open /dev/port: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }
stack backtrace:
   0: rust_begin_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/result.rs:1653:5
   3: std::sys_common::once::futex::Once::call
   4: system76_firmware::firmware_id
   5: system76_firmware_cli::main
```

I'm not sure how exactly this functionality is being used or how deeply it's integrated into the software. 

Are there alternatives to updating system76 firmware that wouldn't require disabling secure boot?
