### ISSUE TITLE
Thelio-io firmware update fails with permission denied error

### ISSUE THREAD

**Issue by brs17** [pop-os/system76-firmware#16]
**Distribution (run `cat /etc/os-release`):**
 Pop!_OS 18.04

**Issue/Bug Description:**
Upon receiving a notification that there is a firmware update available for the thelio-io board, I proceeded with the upgrade and was given an error message that the firmware could not be updated. The logs below describe the issue in greater depth.
 
```
system76-firmware-daemon[1214]:   switching to bootloader
system76-firmware-daemon[1214]: Permission denied (os error 13)
system76-firmware-autostart.desktop[2595]: 2019-07-25 07:28:15,367  ERROR  Failed to install Thelio Io firmware
system76-firmware-autostart.desktop[2595]: Traceback (most recent call last):
system76-firmware-autostart.desktop[2595]:   File "/usr/lib/python3/dist-packages/system76driver/firmware.py", line 489, in _run_firmware_updater
system76-firmware-autostart.desktop[2595]:     iface.ThelioIoUpdate(digest)
system76-firmware-autostart.desktop[2595]:   File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
system76-firmware-autostart.desktop[2595]:     **keywords)
system76-firmware-autostart.desktop[2595]:   File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
system76-firmware-autostart.desktop[2595]:     message, timeout)
system76-firmware-autostart.desktop[2595]: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Failed: Permission denied (os error 13)

```

**Comment by brs17** [comment]
This just happened on a thelio-r1. I believe earlier in the week we saw it happen on a thelio-b1.

**Comment by brs17** [comment]
Upon rebooting, there seems to be no available update anymore. `system76-firmware --thelio_io --notification` shows that the board is now up-to-date.

**Comment by lcbpublic** [comment]
Just had this happen on a Thelio Major (AMD) running Pop!_OS 19.04.  Attempting the update via the "normal" method (click on the notification, etc.) produces the following error message: "rror in system76-firmware client: calling ThelioIoUpdate method failed: "Permission denied (os error 13)".  Attempting the update from a root terminal using 'system76-firmware-cli thelio-io' produces the following output:

root@harry:~# system76-firmware-cli  thelio-io
downloading manifest.json
downloading metadata.json
downloading main.hex
Switching devices to bootloader
 "/sys/bus/usb/devices/1-12"
  revision: ""
  switching to bootloader
system76-firmware: failed to update: Permission denied (os error 13)

On reboot I still get the notification that firmware updates are available.

**Comment by colinbes** [comment]
I am seeing same behavior with Thelio with System76 Thelio I/O board running Ubuntu 18.04

Running cli as sudo also produces same result

**Comment by digitalcfk** [comment]
![thelio-firmware-error](https://user-images.githubusercontent.com/63015648/102514015-94ecaf00-4051-11eb-96d5-8e4c4413c035.png)

Just got this error today. The CLI update method mentioned on the [firmware support page](https://support.system76.com/articles/system-firmware/) didn't help. It ran and did it's thing, but I still see an update. 

Also tried:
```
cfk@thelio:~$ sudo system76-firmware-cli thelio-io
downloading manifest.json
downloading metadata.json
downloading main.hex
Switching devices to bootloader
 "/sys/bus/usb/devices/3-5"
  revision: ""
  switching to bootloader
system76-firmware: failed to update: Permission denied (os error 13)
```

**Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
```

This issue hasn't had any movement in over a year and it's the only result when googling the error message. For the other people that were reporting this problem did you find a fix?

**Comment by willdrew** [comment]
:point_up: Likewise

However, I only noticed this after trying mainline kernel v5.10.1 and v5.10.2 (has issues rebooting and fans remain on as well).  Not surprisingly, I reverted back to `5.8.0-7630-generic` and all is good again with the Thelio I/O version showing up as 1.0.2 ... figured I would share in case anyone else ran into a similar issue.

**Comment by digitalcfk** [comment]
> point_up Likewise
> 
> However, I only noticed this after trying mainline kernel v5.10.1 and v5.10.2 (has issues rebooting and fans remain on as well). Not surprisingly, I reverted back to `5.8.0-7630-generic` and all is good again with the Thelio I/O version showing up as 1.0.2 ... figured I would share in case anyone else ran into a similar issue.

Thanks for that info. I am also using mainline 5.10 because 5.8 has some issues with my monitor setup. Will just ignore for now.

**Comment by LiberalArtist** [comment]
> Just had this happen on a Thelio Major (AMD) running Pop!_OS 19.04. Attempting the update via the "normal" method (click on the notification, etc.) produces the following error message: "rror in system76-firmware client: calling ThelioIoUpdate method failed: "Permission denied (os error 13)". Attempting the update from a root terminal using 'system76-firmware-cli thelio-io' produces the following output:
> 
> ```
> root@harry:~# system76-firmware-cli thelio-io
> downloading manifest.json
> downloading metadata.json
> downloading main.hex
> Switching devices to bootloader
> "/sys/bus/usb/devices/1-12"
> revision: ""
> switching to bootloader
> system76-firmware: failed to update: Permission denied (os error 13)
> ```
> 
> On reboot I still get the notification that firmware updates are available.

I'm having the same error on a Thelio Mira running Debian Bookworm.

**Comment by storrence97** [comment]
I just had this happen when I updated my Thelio Mira from Fedora 38 to 39.  Reinstalling the system76-* packages and rebooting fixed it for me.

**Comment by lrvega** [comment]
> I just had this happen when I updated my Thelio Mira from Fedora 38 to 39. Reinstalling the system76-* packages and rebooting fixed it for me.

I'm running Linux Mint 22. Marking the packages for re-installation and rebooting did not work for me. I had to completely remove the packages, reboot, re-add the ppa, install system-76-driver and reboot. Seems the kernel module is not compiled in a way that works? 

Link for the ppa addition/install in case instructions change in the future: https://support.system76.com/articles/system76-driver/
